apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-system
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
    - chart: base
      repoURL: https://istio-release.storage.googleapis.com/charts
      targetRevision: 1.30.1
      helm:
        releaseName: istio-base
    - chart: istiod
      repoURL: https://istio-release.storage.googleapis.com/charts
      targetRevision: 1.30.1
      helm:
        releaseName: istiod
        valueFiles:
          - $values/gitops/helm/kube-tools/istio-system/values-istiod.yaml
    - chart: cni
      repoURL: https://istio-release.storage.googleapis.com/charts
      targetRevision: 1.30.1
      helm:
        releaseName: istio-cni
        valueFiles:
          - $values/gitops/helm/kube-tools/istio-system/values-cni.yaml
    - chart: ztunnel
      repoURL: https://istio-release.storage.googleapis.com/charts
      targetRevision: 1.30.1
      helm:
        releaseName: ztunnel
    - repoURL: https://github.com/jdarguello/EnterpriseClaw
      targetRevision: main
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: istio-system
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[].clientConfig.caBundle
        - .webhooks[].clientConfig.service.port
        - .webhooks[].failurePolicy
        - .webhooks[].matchPolicy
        - .webhooks[].namespaceSelector
        - .webhooks[].rules[].scope
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[].clientConfig.caBundle
        - .webhooks[].clientConfig.service.port
        - .webhooks[].failurePolicy
        - .webhooks[].matchPolicy
        - .webhooks[].namespaceSelector
        - .webhooks[].rules[].scope
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
