apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default
  sources:
    - chart: external-secrets
      repoURL: https://charts.external-secrets.io
      targetRevision: 0.10.5
      helm:
        releaseName: external-secrets
        valueFiles:
          - $values/gitops/helm/kube-essentials/external-secrets/values.yaml
    - repoURL: https://github.com/jdarguello/EnterpriseClaw
      targetRevision: main
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true