external-secrets:
  global:
    nodeSelector:
      role: backend
  nodeSelector:
      role: backend
  webhook:
    nodeSelector:
      role: backend
  certController:
    nodeSelector:
      role: backend