apiVersion: v2
name: istio
description: Instalación de Istio
type: application
version: 1.28.0

dependencies:
  - name: base
    version: 1.28.0
    repository: https://istio-release.storage.googleapis.com/charts
  - name: istiod
    version: 1.28.0
    repository: https://istio-release.storage.googleapis.com/charts
  - name: cni
    version: 1.28.0
    repository: https://istio-release.storage.googleapis.com/charts
  - name: ztunnel
    version: 1.28.0
    repository: https://istio-release.storage.googleapis.com/charts