istiod:
  nodeSelector:
    eks.amazonaws.com/nodegroup: backend-workers-20251208182115493900000014
  global:
    waypoint:
      nodeSelector:
        eks.amazonaws.com/nodegroup: backend-workers-20251208182115493900000014
