apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: webhook-secret
  namespace: argo-events
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: webhook-secret
    kind: SecretStore
  target:
    name: webhook-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      metadata:
        labels:
          events.argoproj.io/secret-type: repo-creds
  dataFrom:
  - extract:
      key: InnerSource-Webhook-Secret