apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-app-secrets
  namespace: argo
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretstore
    kind: SecretStore
  target:
    name: github-app-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      metadata:
        labels:
          workflows.argoproj.io/secret-type: repo-creds
  dataFrom:
  - extract:
      key: InnerSource-App-Token