apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-workflow-pipe-storage
subjects:
  - kind: ServiceAccount
    name: pipe-storage
    namespace: argo
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
