apiVersion: v2
name: alb-controller
description: Chart para instalar AWS Load Balancer Controller
type: application
version: 1.14.1

dependencies:
  - name: aws-load-balancer-controller
    version: 1.14.1
    repository: https://aws.github.io/eks-charts