apiVersion: v2
name: argo
description: Chart para instalar Argo Workflows
type: application
version: 0.1.0

dependencies:
  - name: argo-workflows
    version: 0.45.27
    repository: https://argoproj.github.io/argo-helm